# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rubylogs.com" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Ruby/Logs
  avatar: avatar.svg
  gravatar: # Email MD5 hash
  description: "Ruby/Logs is a blog with focus on Ruby, Rails, JavaScript, Object-Oriented Design, Open Source technologies and everything in between. Authored by Ilija Eftimov" # used by search engines

  # Header and footer text
  header_text: 
  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a>

  # Icons
  rss: true
  email_address: "ileeftimov+rubylogs@gmail.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "fteem"
  google_plus:
  instagram:
  linkedin: "http://mk.linkedin.com/in/ieftimov/" # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "fteem"
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-11264459-3"
  disqus_shortname: "rubylogs"
  katex: false # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# PAGINATION
paginate: 10
paginate_path: "page:num"

permalink: :title

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
